import PDFDocument from "pdfkit";

export const generatePdf = async (data) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
      info: {
        Title: data.title || "Agent-Flow-AI PDF",
        Author: "Agent-Flow-AI",
        Creator: "Agent-Flow-AI",
      },
    });
    // These are the default events that PDFKit emits when generating a PDF. We can listen to these events to get the generated PDF data.
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", (err) => reject(err));

    // Title
    doc
      .fontSize(28)
      .text(data.title || "Agent-Flow-AI PDF", { align: "center" })
      .fillColor("#111827");

    if (data.subtitle) {
      doc.moveDown(0.5);
    }

    //    Subtitle
    doc
      .fontSize(12)
      .text(data.subtitle || "Generated by Agent-Flow-AI", { align: "center" })
      .fillColor("#6B7280");

    doc.moveDown(2);


data?.sections?.forEach(sec => {
    
  doc
      .fontSize(18)
      .text(sec.heading)
      .fillColor("#111827");

      doc.moveDown(0.5);

      sec?.points?.forEach(point => {
        doc
          .fontSize(12)
          .text("• "+ point,{
            lineGap:5
          })
          .fillColor("#374151");
      })
      doc.moveDown()

});
doc.moveDown()
  doc
      .fontSize(10)
      .text("Generated By Agent-Flow-AI", { align: "center" })
      .fillColor("#9CA3AF");

doc.end();

  });
};
